## FIRST LINE/ROW: Info & Status
# First param ─┌
[username]
format = " [╭─$user]($style)-> "
style_user = "#f8c49c"
style_root = "bold red"
show_always = true

# Second param
[hostname]
format = "[$hostname]($style)"
style = "#a87494"
trim_at = "-"
ssh_only = false
disabled = false

# Third param
[directory]
style = "#c5c8c6"
truncation_length = 0
truncate_to_repo = true
truncation_symbol = "repo: "

# Before all the version info (python, nodejs, php, etc.)
[git_status]
style = "white"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
deleted = "x"

# Last param in the first line/row
[cmd_duration]
min_time = 1
format = " [$duration]($style)"
disabled = false

# Prompt: optional param 1
[time]
format = "  $time($style)\n"
time_format = "%T"
style = "bright-white"
disabled = true

# Prompt: param 2 └─
[character]
success_symbol = " [❄️  ](#f8c49c)"
error_symbol = " [×](bold red)"

# SYMBOLS
[status]
symbol = "🔴"
format = '[\[$symbol$status_common_meaning$status_signal_name$status_maybe_int\]]($style)'
map_symbol = true
disabled = false
