#! /bin/sh

#####################################################
#   ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗   #
#   ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║   #
#   ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║   #
#   ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║   #
#   ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║   #
#   ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝   #                                    
####################### ice #########################

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         0
bspc config window_gap          17
config left_padding 46

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#picom
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#walpapers
## launch polybar

xrdb merge ~/random/st/xresources
[ ! -s ~/.config/mpd/pid ] && mpd
dunst &
exec /home/ice/.config/polybar/launch.sh ./launch &
exec ~/bin/hello.sh &
feh --randomize --bg-scale ~/.config/wallpapers/walls/angel.png
exec ~/bin/water.sh &
polybar --experimental-backends
redshift -P -O 3800 &

picom --experimental-backends --config $HOME/.config/picom/picom.config &
